check the msg_id field instead of the Resultsdb ID when pushing from CentOS to Fedora
jeremycline/rdbsync pull request #2
Opened 2018-10-31 21:31 UTC by bstinsonmhk

2018-10-31 21:38 UTC, puiterwijk requested changes

2018-10-31 21:38 UTC, puiterwijk commented on rdbsync/__init__.py
> +DRY_RUN_HELP = 'Dry run. If selected, print what would have been added to Fedora ResultsDB.'
This seems like an unrelated change. If you want to keep it in one commit, please add it to the commit message?

2018-10-31 21:38 UTC, puiterwijk commented on rdbsync/__init__.py
>              # Grab a list of duplicate result ids - if some of the results
The comment still says we are looking up duplicate result ids.
Maybe this should be updated?

2018-10-31 21:54 UTC, puiterwijk approved these changes

2018-10-31 22:18 UTC, jeremycline approved these changes
Looks fine to me. I'll leave it up to @pypingou to tag and release.

2018-11-02 10:30 UTC, pypingou commented
Thanks for this @bstinsonmhk !

2018-11-02 10:30 UTC, merged